paths:
  data: "./data"
  raw: "${paths.data}/raw" 
  interim: "${paths.data}/interim"
  processed: "${paths.data}/processed"
  external: "${paths.data}/external"
  models: "./models"
  reports: "./reports"
  figures: "${paths.reports}/figures"

data:
  raw_data_file: "${paths.raw}/energy_modified.csv"
  interim_data_file: "${paths.interim}/energy_modified_clean.csv"
  processed_data:
    x_train_file: "${paths.processed}/Xtrain_processed.csv"
    x_test_file: "${paths.processed}/Xtest_processed.csv"
    y_train_file: "${paths.processed}/ytrain_processed.csv"
    y_test_file: "${paths.processed}/ytest_processed.csv"
  models_data:
    model_xgb_file: "${paths.models}/model_xgb.pkl"

cleaning:
  skew_threshold: 0.5

download:
  dataset_id: "1OuJHPpn2Wv5EhlL1J98HWYyPJM-iL8Ds"

preprocessing:
  drop_columns: ["mixed_type_col"]
  target_columns: ["Y1", "Y2"]
  test_size: 0.2
  random_state: 42
  target_transform: "yeo-johnson"
  encoding:
    drop: "first"
    sparse_output: false
    handle_unknown: "ignore"

training:
  random_state: 42
  experiment_name: "xgb_multioutput"
  registry_model_name: "XGBMultiOutput"

transform:
  target_method: "yeo-johnson"
  encoding:
    strategy: "onehot"
    drop: "first"
    handle_unknown: "ignore"
    sparse_output: false

metadata:
  author: "Equipo 38"
  project: "MLops_E38_F2"
  version: "1.0.0"