paths:
  data: "data"
  raw: "${paths.data}/raw" 
  interim: "${paths.data}/interim"
  processed: "${paths.data}/processed"
  external: "${paths.data}/external"
  models: "${paths.data}/models"
  reports: "${paths.data}/reports"
  figures: "${paths.data}/figures"

cleaning:
  input_file: "energy_modified.csv"
  output_file: "energy_modified_clean.csv"
  skew_threshold: 0.5

data:
  input_file: "data/interim/energy_modified_clean.csv"
  output_dir: "data/processed/"
  drop_columns: ["mixed_type_col"]
  target_columns: ["Y1", "Y2"]

download:
  dataset_id: "1OuJHPpn2Wv5EhlL1J98HWYyPJM-iL8Ds"
  dataset_filename: "energy_modified.csv"

preprocessing:
  input_file: "energy_modified_clean.csv"
  output_files:
    x_train: "Xtrain_processed.csv"
    x_test: "Xtest_processed.csv"
    y_train: "ytrain_processed.csv"
    y_test: "ytest_processed.csv"
  drop_columns: ["mixed_type_col"]
  target_columns: ["Y1", "Y2"]
  test_size: 0.2
  random_state: 42
  target_transform: "yeo-johnson"
  encoding:
    drop: "first"
    sparse_output: false
    handle_unknown: "ignore"

training:
  model_filename: "model_xgb.pkl"
  random_state: 42
  metrics_file_xgb: "metrics_xgb.txt"
  experiment_name: "xgb_multioutput"

transform:
  target_method: "yeo-johnson"
  encoding:
    strategy: "onehot"
    drop: "first"
    handle_unknown: "ignore"
    sparse_output: false

metadata:
  author: "Equipo 38"
  project: "MLops_E38_F2"
  version: "1.0.0"